[package]
name = "antic-sys"
version = "0.1.0"
edition = "2018"
authors = ["William Youmans <wyoumans@usf.edu>"]
description = "Bindings to the Antic library"
homepage = "https://github.com/wyoumansUSF/antic-sys"
repository = "https://github.com/wyoumansUSF/antic-sys"
license = "LGPL-3.0+" 
keywords = ["flint", "number-theory", "math"]
categories = ["algorithms", "external-ffi-bindings", "mathematics"]
readme = "README.md"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
flint-sys = "0.4"
